version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - DMZ-WAN
    ports:
      - "80:80"
      - "443:8443"
    volumes:
      - ./Caddyfile:/data/Caddyfile
      - data:/data
      - config:/config
    environment:
      - TZ=Europe/Berlin

volumes:
  data:
  config:

networks:
  DMZ-WAN:
    external: true
