version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      internal: {}
    restart: unless-stopped
    volumes:
     - bitwarden:/data:rw
    environment:
#     - ROCKET_TLS={certs="/data/ssl/certs.pem",key="/data/ssl/key.pem"} 
     - ROCKET_PORT=80
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=true
     - DOMAIN=${DOMAIN}
volumes:
  bitwarden:
networks:
  internal:
    external: true