version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      Server:
        ipv4_address: ${IPV4_ADDRESS}
        mac_address: ${MAC_ADDRESS}
    restart: unless-stopped
    ports:
     - 9445:80 #map any custom port to use (replace 9445 not 80)
    volumes:
     - bitwarden:/data:rw
    environment:
#     - ROCKET_TLS={certs="/ssl/certs/certs.pem",key="/ssl/private/key.pem"}  // Environment variable is specific to the Rocket web server
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=true ##change to false once create the admin account
     - DOMAIN=${DOMAIN}
volumes:
  bitwarden:
networks:
  Server:
    external:
      name: Server